# Change these first
owner: Trunkstar
repo: status

sites:
  - name: API Production
    url: https://api.trunkstar.com/status
  - name: Website Production
    url: https://trunkstar.com
  - name: Platform Production
    url: https://platform.trunkstar.com
    
  - name: API Staging
    url: https://api.staging.trunkstar.com/status
  - name: Website Staging
    url: https://website.staging.trunkstar.com
  - name: Platform Staging
    url: https://platform.staging.trunkstar.com
    
status-website:
  cname: status.trunkstar.com
#   baseUrl: /upptime
#   logoUrl: https://raw.githubusercontent.com/Trunkstar/upptime/master/assets/logo-dark.svg 
  logoUrl: https://raw.githubusercontent.com/Trunkstar/status/master/assets/upptime-icon.svg
  name: ""
  introTitle: "**Trunkstar** status"
  introMessage: Wholesale SIP trunking platform
  navbar:
    - title: Trunkstar
      href: https://trunkstar.com
    - title: Status
      href: /
      
# workflowSchedule:
#   graphs: "0 0 * * *"
#   responseTime: "0 23 * * *"
#   staticSite: "0 1 * * *"
#   summary: "0 0 * * *"
#   updateTemplate: "0 0 * * *"
#   updates: "0 3 * * *"
#   uptime: "*/2 * * * *"
  
# Upptime also supports notifications, assigning issues, and more 
# See https://upptime.js.org/docs/configuration
